### ISSUE TITLE
Background Timer calculations are being performed regardless of the timer state

### ISSUE THREAD

**Issue by waqas-334** [haidern21/vipassana#37]
Even if the timer is not running and the app goes into the paused state for some reason say Google Sign In the popup, and when it comes back to the Resumed state, it does all those calculations. Which it should not.

### Possible Solution
Put a boolean variable in sharedPreferences to check if the timer was either running or not. If not then no need to perform further calculations.

**Comment by haidern21** [comment]
Implemented your suggested solution and it worked
